apiVersion: v1
kind: Service
metadata:
  name: pythonhttp-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: pythonhttp 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
